package password

import (
	"context"
	"encoding/hex"
	"errors"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"
)

func newTestVerifier(t *testing.T, limits Limits) *Verifier {
	t.Helper()
	v, err := NewVerifier(limits)
	if err != nil {
		t.Fatal(err)
	}
	return v
}

func TestVerifyPublicVector(t *testing.T) {
	v := newTestVerifier(t, testLimits())
	if err := v.Verify(context.Background(), "password", vectorPHC()); err != nil {
		t.Fatalf("public vector failed: %v", err)
	}
	for _, password := range []string{"wrong", " password", "password ", "PASSWORD", "", "password\x00", "密码"} {
		if err := v.Verify(context.Background(), password, vectorPHC()); !errors.Is(err, ErrPassword) {
			t.Fatalf("nonmatching password: %v", err)
		}
	}
}

func TestVerifyPublicMultiPassAndParallelVectors(t *testing.T) {
	// Fixed expected bytes are copied from golang.org/x/crypto v0.53.0,
	// argon2/argon2_test.go TestVectors (lines 158, 170 and 182). All use
	// password="password", salt="somesalt", version 19 and 24 output bytes.
	// They are not generated by the verifier or its derive function.
	for _, test := range []struct {
		parameters string
		hash       string
	}{
		{"m=64,t=2,p=1", "068d62b26455936aa6ebe60060b0a65870dbfa3ddf8d41f7"},
		{"m=64,t=2,p=2", "350ac37222f436ccb5c0972f1ebd3bf6b958bf2071841362"},
		{"m=256,t=3,p=2", "4668d30ac4187e6878eedeacf0fd83c5a0a30db2cc16ef0b"},
	} {
		t.Run(test.parameters, func(t *testing.T) {
			hash, err := hex.DecodeString(test.hash)
			if err != nil {
				t.Fatal("invalid public test fixture")
			}
			v := newTestVerifier(t, testLimits())
			encoded := phcWith(test.parameters, []byte("somesalt"), hash)
			if err := v.Verify(context.Background(), "password", encoded); err != nil {
				t.Fatalf("public multi-pass/parallel vector: %v", err)
			}
			if err := v.Verify(context.Background(), "wrong", encoded); !errors.Is(err, ErrPassword) {
				t.Fatalf("wrong password for public vector: %v", err)
			}
		})
	}
}

func TestVerifyPublicVectorsPreserveNonDivisibleDeclaredMemory(t *testing.T) {
	// These fixed upstream TestVectors (argon2/argon2_test.go lines 218 and
	// 230) declare memory not divisible by 4*p. The KDF rounds the allocated
	// blocks down, but hashes the original declared memory into its initial
	// state. Changing only PHC m to that rounded value must not verify.
	// Expected hashes below are upstream constants, not locally derived values.
	for _, test := range []struct {
		parameters string
		rounded    string
		memory     uint32
		hash       string
	}{
		{"m=64,t=2,p=3", "m=60,t=2,p=3", 64, "4a15b31aec7c2590b87d1f520be7d96f56658172deaa3079"},
		{"m=1024,t=3,p=6", "m=1008,t=3,p=6", 1024, "1640b932f4b60e272f5d2207b9a9c626ffa1bd88d2349016"},
	} {
		t.Run(test.parameters, func(t *testing.T) {
			hash, err := hex.DecodeString(test.hash)
			if err != nil {
				t.Fatal("invalid public test fixture")
			}
			limits := testLimits()
			limits.MaxParallelism = 6 // Explicit policy for these public fixtures.
			v := newTestVerifier(t, limits)
			encoded := phcWith(test.parameters, []byte("somesalt"), hash)
			params, err := parse(encoded, limits)
			if err != nil || params.memory != test.memory {
				t.Fatalf("declared memory changed during PHC parsing: %v", err)
			}
			if err := v.Verify(context.Background(), "password", encoded); err != nil {
				t.Fatalf("public non-divisible memory vector: %v", err)
			}
			if err := v.Verify(context.Background(), "password", phcWith(test.rounded, []byte("somesalt"), hash)); !errors.Is(err, ErrPassword) {
				t.Fatalf("rounded memory declaration reused original hash: %v", err)
			}
		})
	}
}

func TestRejectsBeforeKDF(t *testing.T) {
	limits := testLimits()
	limits.MaxWorkKiB = 64
	v := newTestVerifier(t, limits)
	var calls atomic.Int32
	v.derive = func(_, _ []byte, _, _ uint32, _ uint8, _ uint32) []byte {
		calls.Add(1)
		return vectorHash()
	}
	for _, test := range []struct {
		name     string
		password string
		phc      string
		want     error
	}{
		{"input length", strings.Repeat("s", limits.MaxPasswordBytes+1), vectorPHC(), ErrPasswordPolicy},
		{"malformed PHC", "password", "invalid synthetic hash", ErrInvalidHash},
		{"memory", "password", phcWith("m=2048,t=1,p=1", []byte("somesalt"), vectorHash()), ErrHashPolicy},
		{"work", "password", phcWith("m=64,t=2,p=1", []byte("somesalt"), vectorHash()), ErrHashPolicy},
		{"zero passes", "password", phcWith("m=64,t=0,p=1", []byte("somesalt"), vectorHash()), ErrInvalidHash},
		{"zero parallelism", "password", phcWith("m=64,t=1,p=0", []byte("somesalt"), vectorHash()), ErrInvalidHash},
	} {
		t.Run(test.name, func(t *testing.T) {
			if err := v.Verify(context.Background(), test.password, test.phc); !errors.Is(err, test.want) {
				t.Fatalf("got %v, want %v", err, test.want)
			}
		})
	}
	if calls.Load() != 0 {
		t.Fatal("rejected input reached KDF")
	}
}

func TestVerifierPreservesPasswordBytesAndInclusiveLimit(t *testing.T) {
	limits := testLimits()
	password := " A密码\x00 "
	limits.MaxPasswordBytes = len(password)
	v := newTestVerifier(t, limits)
	var received []byte
	var derived []byte
	v.derive = func(value, _ []byte, _, _ uint32, _ uint8, _ uint32) []byte {
		if string(value) != password {
			t.Fatal("verifier normalized password bytes")
		}
		received = value
		derived = vectorHash()
		return derived
	}
	if err := v.Verify(context.Background(), password, vectorPHC()); err != nil {
		t.Fatal(err)
	}
	for _, buffer := range [][]byte{received, derived} {
		for _, b := range buffer {
			if b != 0 {
				t.Fatal("temporary verifier buffer was not cleared")
			}
		}
	}
}

func TestPreCanceledContextDoesNotStartKDF(t *testing.T) {
	v := newTestVerifier(t, testLimits())
	var calls atomic.Int32
	v.derive = func(_, _ []byte, _, _ uint32, _ uint8, _ uint32) []byte {
		calls.Add(1)
		return vectorHash()
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if err := v.Verify(ctx, "password", vectorPHC()); !errors.Is(err, context.Canceled) {
		t.Fatalf("canceled context: %v", err)
	}
	expired, stop := context.WithDeadline(context.Background(), time.Now().Add(-time.Second))
	defer stop()
	if err := v.Verify(expired, "password", vectorPHC()); !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("expired context: %v", err)
	}
	if err := v.Verify(nil, "password", vectorPHC()); !errors.Is(err, ErrInvalidContext) {
		t.Fatalf("nil context: %v", err)
	}
	if calls.Load() != 0 {
		t.Fatal("canceled context reached KDF")
	}
	if err := v.Verify(context.Background(), "password", vectorPHC()); err != nil {
		t.Fatalf("cancellation leaked capacity: %v", err)
	}
}

func TestRunningCancellationKeepsSlotUntilKDFFinishes(t *testing.T) {
	limits := testLimits()
	limits.MaxConcurrent = 1
	v := newTestVerifier(t, limits)
	started := make(chan struct{}, 2)
	finish := make(chan struct{})
	var release sync.Once
	t.Cleanup(func() { release.Do(func() { close(finish) }) })
	v.derive = func(_, _ []byte, _, _ uint32, _ uint8, _ uint32) []byte {
		started <- struct{}{}
		<-finish
		return vectorHash()
	}
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	result := make(chan error, 1)
	go func() { result <- v.Verify(ctx, "password", vectorPHC()) }()
	waitStarted(t, started)
	cancel()
	if err := v.Verify(context.Background(), "password", vectorPHC()); !errors.Is(err, ErrBusy) {
		t.Fatalf("running cancellation released capacity: %v", err)
	}
	select {
	case <-result:
		t.Fatal("Verify returned while KDF remained active")
	default:
	}
	release.Do(func() { close(finish) })
	if err := waitResult(t, result); !errors.Is(err, context.Canceled) {
		t.Fatalf("canceled computation returned success: %v", err)
	}
	if err := v.Verify(context.Background(), "password", vectorPHC()); err != nil {
		t.Fatalf("completed computation leaked capacity: %v", err)
	}
}

func TestFullCapacityRejectsWithoutQueue(t *testing.T) {
	v := newTestVerifier(t, testLimits())
	started := make(chan struct{}, 2)
	finish := make(chan struct{})
	var release sync.Once
	t.Cleanup(func() { release.Do(func() { close(finish) }) })
	var calls atomic.Int32
	v.derive = func(_, _ []byte, _, _ uint32, _ uint8, _ uint32) []byte {
		calls.Add(1)
		started <- struct{}{}
		<-finish
		return vectorHash()
	}
	result := make(chan error, 2)
	for range 2 {
		go func() { result <- v.Verify(context.Background(), "password", vectorPHC()) }()
		waitStarted(t, started)
	}
	third := make(chan error, 1)
	go func() { third <- v.Verify(context.Background(), "password", vectorPHC()) }()
	if err := waitResult(t, third); !errors.Is(err, ErrBusy) {
		t.Fatalf("full verifier: %v", err)
	}
	if calls.Load() != 2 {
		t.Fatal("too many KDFs admitted")
	}
	release.Do(func() { close(finish) })
	for range 2 {
		if err := waitResult(t, result); err != nil {
			t.Fatal(err)
		}
	}
}

func TestConcurrentRealKDF(t *testing.T) {
	v := newTestVerifier(t, testLimits())
	var group sync.WaitGroup
	var successes atomic.Int32
	for range 12 {
		group.Add(1)
		go func() {
			defer group.Done()
			for range 12 {
				err := v.Verify(context.Background(), "password", vectorPHC())
				if err == nil {
					successes.Add(1)
				} else if !errors.Is(err, ErrBusy) {
					t.Errorf("concurrent verification: %v", err)
				}
			}
		}()
	}
	group.Wait()
	if successes.Load() == 0 {
		t.Fatal("no computation completed")
	}
	if err := v.Verify(context.Background(), "password", vectorPHC()); err != nil {
		t.Fatalf("concurrent calls leaked capacity: %v", err)
	}
}

func TestErrorsDoNotContainInputs(t *testing.T) {
	v := newTestVerifier(t, testLimits())
	password, phc := "sensitive-synthetic-marker", "sensitive-synthetic-hash"
	for _, err := range []error{
		v.Verify(context.Background(), password, phc),
		v.Verify(context.Background(), password, vectorPHC()),
		v.Verify(context.Background(), strings.Repeat(password, 100), vectorPHC()),
	} {
		if err == nil || strings.Contains(err.Error(), password) || strings.Contains(err.Error(), phc) || strings.Contains(err.Error(), vectorPHC()) {
			t.Fatal("error contains an input or unexpectedly succeeded")
		}
	}
}

func waitStarted(t *testing.T, started <-chan struct{}) {
	t.Helper()
	select {
	case <-started:
	case <-time.After(3 * time.Second):
		t.Fatal("synthetic KDF did not start")
	}
}

func waitResult(t *testing.T, result <-chan error) error {
	t.Helper()
	select {
	case err := <-result:
		return err
	case <-time.After(3 * time.Second):
		t.Fatal("verification did not finish")
		return nil
	}
}
