CREATE TABLE onboarding_intents (
    intent_id CHAR(36) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    account_id VARCHAR(128) NOT NULL,
    desired_generation BIGINT UNSIGNED NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    auth_type VARCHAR(32) NOT NULL,
    ciphertext LONGBLOB NOT NULL,
    encrypted_dek BLOB NOT NULL,
    nonce BINARY(12) NOT NULL,
    aad_json BLOB NOT NULL,
    kms_key_id VARCHAR(255) NOT NULL,
    kms_key_version VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    claim_owner VARCHAR(128) NOT NULL DEFAULT '',
    claim_expires_at DATETIME(6) NULL,
    expires_at DATETIME(6) NOT NULL,
    consumed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (intent_id),
    UNIQUE KEY uq_onboarding_intents_idempotency (idempotency_key),
    KEY idx_onboarding_intents_expiry (status, expires_at),
    KEY idx_onboarding_intents_claim (status, claim_expires_at),
    CONSTRAINT chk_onboarding_intents_generation CHECK (desired_generation > 0),
    CONSTRAINT chk_onboarding_intents_status CHECK (status IN ('pending', 'claimed', 'consumed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
