CREATE TABLE onboarding_workflows (
    workflow_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    intent_id CHAR(36) NOT NULL,
    claim_owner VARCHAR(128) NOT NULL,
    account_id VARCHAR(128) NOT NULL,
    desired_generation BIGINT UNSIGNED NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    slot_id VARCHAR(128) NOT NULL,
    execution_epoch BIGINT UNSIGNED NOT NULL,
    image_digest VARCHAR(128) NOT NULL,
    credential_lease_id VARCHAR(128) NOT NULL,
    proxy_lease_id VARCHAR(128) NOT NULL,
    key_command_id VARCHAR(128) NOT NULL,
    activation_command_id VARCHAR(128) NOT NULL,
    command_deadline DATETIME(6) NOT NULL,
    status VARCHAR(32) NOT NULL,
    key_id VARCHAR(128) NOT NULL DEFAULT '',
    key_public_key BINARY(32) NULL,
    error_code VARCHAR(64) NOT NULL DEFAULT '',
    last_command_id VARCHAR(128) NOT NULL DEFAULT '',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (workflow_id),
    UNIQUE KEY uq_onboarding_workflows_idempotency (idempotency_key),
    UNIQUE KEY uq_onboarding_workflows_credential_lease (credential_lease_id),
    UNIQUE KEY uq_onboarding_workflows_key_command (key_command_id),
    UNIQUE KEY uq_onboarding_workflows_activation_command (activation_command_id),
    KEY idx_onboarding_workflows_status (status, updated_at),
    KEY idx_onboarding_workflows_account_generation (account_id, desired_generation),
    CONSTRAINT fk_onboarding_workflows_intent FOREIGN KEY (intent_id) REFERENCES onboarding_intents(intent_id),
    CONSTRAINT fk_onboarding_workflows_slot FOREIGN KEY (slot_id) REFERENCES slots(slot_id),
    CONSTRAINT chk_onboarding_workflows_generation CHECK (desired_generation > 0),
    CONSTRAINT chk_onboarding_workflows_epoch CHECK (execution_epoch > 0),
    CONSTRAINT chk_onboarding_workflows_status CHECK (status IN (
        'pending_key', 'key_dispatched', 'key_ready', 'activation_dispatched', 'activation_succeeded', 'failed', 'completed'
    ))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
