// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: execution/v1/dataplane.proto

package executionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionDataPlaneService_Execute_FullMethodName     = "/execution.v1.ExecutionDataPlaneService/Execute"
	ExecutionDataPlaneService_CountTokens_FullMethodName = "/execution.v1.ExecutionDataPlaneService/CountTokens"
	ExecutionDataPlaneService_ListModels_FullMethodName  = "/execution.v1.ExecutionDataPlaneService/ListModels"
)

// ExecutionDataPlaneServiceClient is the client API for ExecutionDataPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutionDataPlaneServiceClient interface {
	Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteRequest, ExecuteResponse], error)
	CountTokens(ctx context.Context, in *CountTokensRequest, opts ...grpc.CallOption) (*CountTokensResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
}

type executionDataPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionDataPlaneServiceClient(cc grpc.ClientConnInterface) ExecutionDataPlaneServiceClient {
	return &executionDataPlaneServiceClient{cc}
}

func (c *executionDataPlaneServiceClient) Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteRequest, ExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecutionDataPlaneService_ServiceDesc.Streams[0], ExecutionDataPlaneService_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionDataPlaneService_ExecuteClient = grpc.BidiStreamingClient[ExecuteRequest, ExecuteResponse]

func (c *executionDataPlaneServiceClient) CountTokens(ctx context.Context, in *CountTokensRequest, opts ...grpc.CallOption) (*CountTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountTokensResponse)
	err := c.cc.Invoke(ctx, ExecutionDataPlaneService_CountTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionDataPlaneServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ExecutionDataPlaneService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionDataPlaneServiceServer is the server API for ExecutionDataPlaneService service.
// All implementations must embed UnimplementedExecutionDataPlaneServiceServer
// for forward compatibility.
type ExecutionDataPlaneServiceServer interface {
	Execute(grpc.BidiStreamingServer[ExecuteRequest, ExecuteResponse]) error
	CountTokens(context.Context, *CountTokensRequest) (*CountTokensResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	mustEmbedUnimplementedExecutionDataPlaneServiceServer()
}

// UnimplementedExecutionDataPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionDataPlaneServiceServer struct{}

func (UnimplementedExecutionDataPlaneServiceServer) Execute(grpc.BidiStreamingServer[ExecuteRequest, ExecuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedExecutionDataPlaneServiceServer) CountTokens(context.Context, *CountTokensRequest) (*CountTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountTokens not implemented")
}
func (UnimplementedExecutionDataPlaneServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedExecutionDataPlaneServiceServer) mustEmbedUnimplementedExecutionDataPlaneServiceServer() {
}
func (UnimplementedExecutionDataPlaneServiceServer) testEmbeddedByValue() {}

// UnsafeExecutionDataPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionDataPlaneServiceServer will
// result in compilation errors.
type UnsafeExecutionDataPlaneServiceServer interface {
	mustEmbedUnimplementedExecutionDataPlaneServiceServer()
}

func RegisterExecutionDataPlaneServiceServer(s grpc.ServiceRegistrar, srv ExecutionDataPlaneServiceServer) {
	// If the following call pancis, it indicates UnimplementedExecutionDataPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionDataPlaneService_ServiceDesc, srv)
}

func _ExecutionDataPlaneService_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExecutionDataPlaneServiceServer).Execute(&grpc.GenericServerStream[ExecuteRequest, ExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionDataPlaneService_ExecuteServer = grpc.BidiStreamingServer[ExecuteRequest, ExecuteResponse]

func _ExecutionDataPlaneService_CountTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionDataPlaneServiceServer).CountTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionDataPlaneService_CountTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionDataPlaneServiceServer).CountTokens(ctx, req.(*CountTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionDataPlaneService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionDataPlaneServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionDataPlaneService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionDataPlaneServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutionDataPlaneService_ServiceDesc is the grpc.ServiceDesc for ExecutionDataPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionDataPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "execution.v1.ExecutionDataPlaneService",
	HandlerType: (*ExecutionDataPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountTokens",
			Handler:    _ExecutionDataPlaneService_CountTokens_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _ExecutionDataPlaneService_ListModels_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _ExecutionDataPlaneService_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "execution/v1/dataplane.proto",
}
