// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: execution/v1/onboarding.proto

package executionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnboardingSource int32

const (
	OnboardingSource_ONBOARDING_SOURCE_UNSPECIFIED       OnboardingSource = 0
	OnboardingSource_ONBOARDING_SOURCE_SESSION_KEY       OnboardingSource = 1
	OnboardingSource_ONBOARDING_SOURCE_OAUTH_CODE        OnboardingSource = 2
	OnboardingSource_ONBOARDING_SOURCE_SETUP_TOKEN       OnboardingSource = 3
	OnboardingSource_ONBOARDING_SOURCE_API_KEY           OnboardingSource = 4
	OnboardingSource_ONBOARDING_SOURCE_COOKIE            OnboardingSource = 5
	OnboardingSource_ONBOARDING_SOURCE_CREDENTIAL_IMPORT OnboardingSource = 6
)

// Enum value maps for OnboardingSource.
var (
	OnboardingSource_name = map[int32]string{
		0: "ONBOARDING_SOURCE_UNSPECIFIED",
		1: "ONBOARDING_SOURCE_SESSION_KEY",
		2: "ONBOARDING_SOURCE_OAUTH_CODE",
		3: "ONBOARDING_SOURCE_SETUP_TOKEN",
		4: "ONBOARDING_SOURCE_API_KEY",
		5: "ONBOARDING_SOURCE_COOKIE",
		6: "ONBOARDING_SOURCE_CREDENTIAL_IMPORT",
	}
	OnboardingSource_value = map[string]int32{
		"ONBOARDING_SOURCE_UNSPECIFIED":       0,
		"ONBOARDING_SOURCE_SESSION_KEY":       1,
		"ONBOARDING_SOURCE_OAUTH_CODE":        2,
		"ONBOARDING_SOURCE_SETUP_TOKEN":       3,
		"ONBOARDING_SOURCE_API_KEY":           4,
		"ONBOARDING_SOURCE_COOKIE":            5,
		"ONBOARDING_SOURCE_CREDENTIAL_IMPORT": 6,
	}
)

func (x OnboardingSource) Enum() *OnboardingSource {
	p := new(OnboardingSource)
	*p = x
	return p
}

func (x OnboardingSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnboardingSource) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_v1_onboarding_proto_enumTypes[0].Descriptor()
}

func (OnboardingSource) Type() protoreflect.EnumType {
	return &file_execution_v1_onboarding_proto_enumTypes[0]
}

func (x OnboardingSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnboardingSource.Descriptor instead.
func (OnboardingSource) EnumDescriptor() ([]byte, []int) {
	return file_execution_v1_onboarding_proto_rawDescGZIP(), []int{0}
}

type OnboardingAuthType int32

const (
	OnboardingAuthType_ONBOARDING_AUTH_TYPE_UNSPECIFIED OnboardingAuthType = 0
	OnboardingAuthType_ONBOARDING_AUTH_TYPE_OAUTH       OnboardingAuthType = 1
	OnboardingAuthType_ONBOARDING_AUTH_TYPE_SETUP_TOKEN OnboardingAuthType = 2
	OnboardingAuthType_ONBOARDING_AUTH_TYPE_API_KEY     OnboardingAuthType = 3
)

// Enum value maps for OnboardingAuthType.
var (
	OnboardingAuthType_name = map[int32]string{
		0: "ONBOARDING_AUTH_TYPE_UNSPECIFIED",
		1: "ONBOARDING_AUTH_TYPE_OAUTH",
		2: "ONBOARDING_AUTH_TYPE_SETUP_TOKEN",
		3: "ONBOARDING_AUTH_TYPE_API_KEY",
	}
	OnboardingAuthType_value = map[string]int32{
		"ONBOARDING_AUTH_TYPE_UNSPECIFIED": 0,
		"ONBOARDING_AUTH_TYPE_OAUTH":       1,
		"ONBOARDING_AUTH_TYPE_SETUP_TOKEN": 2,
		"ONBOARDING_AUTH_TYPE_API_KEY":     3,
	}
)

func (x OnboardingAuthType) Enum() *OnboardingAuthType {
	p := new(OnboardingAuthType)
	*p = x
	return p
}

func (x OnboardingAuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnboardingAuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_v1_onboarding_proto_enumTypes[1].Descriptor()
}

func (OnboardingAuthType) Type() protoreflect.EnumType {
	return &file_execution_v1_onboarding_proto_enumTypes[1]
}

func (x OnboardingAuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnboardingAuthType.Descriptor instead.
func (OnboardingAuthType) EnumDescriptor() ([]byte, []int) {
	return file_execution_v1_onboarding_proto_rawDescGZIP(), []int{1}
}

// Zero is the legacy-success compatibility value: clients reading responses
// from a server predating this enum treat UNSPECIFIED plus the existing safe
// projection fields as succeeded. New servers always emit an explicit terminal
// value. Pending remains the gRPC FailedPrecondition path.
type OnboardingResultStatus int32

const (
	OnboardingResultStatus_ONBOARDING_RESULT_STATUS_UNSPECIFIED OnboardingResultStatus = 0
	OnboardingResultStatus_ONBOARDING_RESULT_STATUS_SUCCEEDED   OnboardingResultStatus = 1
	OnboardingResultStatus_ONBOARDING_RESULT_STATUS_FAILED      OnboardingResultStatus = 2
	OnboardingResultStatus_ONBOARDING_RESULT_STATUS_EXPIRED     OnboardingResultStatus = 3
)

// Enum value maps for OnboardingResultStatus.
var (
	OnboardingResultStatus_name = map[int32]string{
		0: "ONBOARDING_RESULT_STATUS_UNSPECIFIED",
		1: "ONBOARDING_RESULT_STATUS_SUCCEEDED",
		2: "ONBOARDING_RESULT_STATUS_FAILED",
		3: "ONBOARDING_RESULT_STATUS_EXPIRED",
	}
	OnboardingResultStatus_value = map[string]int32{
		"ONBOARDING_RESULT_STATUS_UNSPECIFIED": 0,
		"ONBOARDING_RESULT_STATUS_SUCCEEDED":   1,
		"ONBOARDING_RESULT_STATUS_FAILED":      2,
		"ONBOARDING_RESULT_STATUS_EXPIRED":     3,
	}
)

func (x OnboardingResultStatus) Enum() *OnboardingResultStatus {
	p := new(OnboardingResultStatus)
	*p = x
	return p
}

func (x OnboardingResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnboardingResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_execution_v1_onboarding_proto_enumTypes[2].Descriptor()
}

func (OnboardingResultStatus) Type() protoreflect.EnumType {
	return &file_execution_v1_onboarding_proto_enumTypes[2]
}

func (x OnboardingResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnboardingResultStatus.Descriptor instead.
func (OnboardingResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_execution_v1_onboarding_proto_rawDescGZIP(), []int{2}
}

type CreateOnboardingIntentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey    string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AccountId         string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DesiredGeneration uint64                 `protobuf:"varint,3,opt,name=desired_generation,json=desiredGeneration,proto3" json:"desired_generation,omitempty"`
	Source            OnboardingSource       `protobuf:"varint,4,opt,name=source,proto3,enum=execution.v1.OnboardingSource" json:"source,omitempty"`
	AuthType          OnboardingAuthType     `protobuf:"varint,5,opt,name=auth_type,json=authType,proto3,enum=execution.v1.OnboardingAuthType" json:"auth_type,omitempty"`
	Secret            []byte                 `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	Auxiliary         []byte                 `protobuf:"bytes,7,opt,name=auxiliary,proto3" json:"auxiliary,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateOnboardingIntentRequest) Reset() {
	*x = CreateOnboardingIntentRequest{}
	mi := &file_execution_v1_onboarding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOnboardingIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOnboardingIntentRequest) ProtoMessage() {}

func (x *CreateOnboardingIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_onboarding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOnboardingIntentRequest.ProtoReflect.Descriptor instead.
func (*CreateOnboardingIntentRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_onboarding_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOnboardingIntentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateOnboardingIntentRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateOnboardingIntentRequest) GetDesiredGeneration() uint64 {
	if x != nil {
		return x.DesiredGeneration
	}
	return 0
}

func (x *CreateOnboardingIntentRequest) GetSource() OnboardingSource {
	if x != nil {
		return x.Source
	}
	return OnboardingSource_ONBOARDING_SOURCE_UNSPECIFIED
}

func (x *CreateOnboardingIntentRequest) GetAuthType() OnboardingAuthType {
	if x != nil {
		return x.AuthType
	}
	return OnboardingAuthType_ONBOARDING_AUTH_TYPE_UNSPECIFIED
}

func (x *CreateOnboardingIntentRequest) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *CreateOnboardingIntentRequest) GetAuxiliary() []byte {
	if x != nil {
		return x.Auxiliary
	}
	return nil
}

type CreateOnboardingIntentResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IntentId          string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	AccountId         string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DesiredGeneration uint64                 `protobuf:"varint,3,opt,name=desired_generation,json=desiredGeneration,proto3" json:"desired_generation,omitempty"`
	Source            OnboardingSource       `protobuf:"varint,4,opt,name=source,proto3,enum=execution.v1.OnboardingSource" json:"source,omitempty"`
	AuthType          OnboardingAuthType     `protobuf:"varint,5,opt,name=auth_type,json=authType,proto3,enum=execution.v1.OnboardingAuthType" json:"auth_type,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateOnboardingIntentResponse) Reset() {
	*x = CreateOnboardingIntentResponse{}
	mi := &file_execution_v1_onboarding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOnboardingIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOnboardingIntentResponse) ProtoMessage() {}

func (x *CreateOnboardingIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_onboarding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOnboardingIntentResponse.ProtoReflect.Descriptor instead.
func (*CreateOnboardingIntentResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_onboarding_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOnboardingIntentResponse) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *CreateOnboardingIntentResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateOnboardingIntentResponse) GetDesiredGeneration() uint64 {
	if x != nil {
		return x.DesiredGeneration
	}
	return 0
}

func (x *CreateOnboardingIntentResponse) GetSource() OnboardingSource {
	if x != nil {
		return x.Source
	}
	return OnboardingSource_ONBOARDING_SOURCE_UNSPECIFIED
}

func (x *CreateOnboardingIntentResponse) GetAuthType() OnboardingAuthType {
	if x != nil {
		return x.AuthType
	}
	return OnboardingAuthType_ONBOARDING_AUTH_TYPE_UNSPECIFIED
}

func (x *CreateOnboardingIntentResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// RecoverOnboardingIntentRequest contains only the exact durable identity of a
// previously-created intent that has not yet been claimed. It deliberately has
// no credential or auxiliary-material field.
type RecoverOnboardingIntentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey    string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AccountId         string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DesiredGeneration uint64                 `protobuf:"varint,3,opt,name=desired_generation,json=desiredGeneration,proto3" json:"desired_generation,omitempty"`
	Source            OnboardingSource       `protobuf:"varint,4,opt,name=source,proto3,enum=execution.v1.OnboardingSource" json:"source,omitempty"`
	AuthType          OnboardingAuthType     `protobuf:"varint,5,opt,name=auth_type,json=authType,proto3,enum=execution.v1.OnboardingAuthType" json:"auth_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecoverOnboardingIntentRequest) Reset() {
	*x = RecoverOnboardingIntentRequest{}
	mi := &file_execution_v1_onboarding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverOnboardingIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverOnboardingIntentRequest) ProtoMessage() {}

func (x *RecoverOnboardingIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_onboarding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverOnboardingIntentRequest.ProtoReflect.Descriptor instead.
func (*RecoverOnboardingIntentRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_onboarding_proto_rawDescGZIP(), []int{2}
}

func (x *RecoverOnboardingIntentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RecoverOnboardingIntentRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RecoverOnboardingIntentRequest) GetDesiredGeneration() uint64 {
	if x != nil {
		return x.DesiredGeneration
	}
	return 0
}

func (x *RecoverOnboardingIntentRequest) GetSource() OnboardingSource {
	if x != nil {
		return x.Source
	}
	return OnboardingSource_ONBOARDING_SOURCE_UNSPECIFIED
}

func (x *RecoverOnboardingIntentRequest) GetAuthType() OnboardingAuthType {
	if x != nil {
		return x.AuthType
	}
	return OnboardingAuthType_ONBOARDING_AUTH_TYPE_UNSPECIFIED
}

type GetOnboardingResultRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IntentId          string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	AccountId         string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DesiredGeneration uint64                 `protobuf:"varint,3,opt,name=desired_generation,json=desiredGeneration,proto3" json:"desired_generation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOnboardingResultRequest) Reset() {
	*x = GetOnboardingResultRequest{}
	mi := &file_execution_v1_onboarding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnboardingResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnboardingResultRequest) ProtoMessage() {}

func (x *GetOnboardingResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_onboarding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnboardingResultRequest.ProtoReflect.Descriptor instead.
func (*GetOnboardingResultRequest) Descriptor() ([]byte, []int) {
	return file_execution_v1_onboarding_proto_rawDescGZIP(), []int{3}
}

func (x *GetOnboardingResultRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *GetOnboardingResultRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetOnboardingResultRequest) GetDesiredGeneration() uint64 {
	if x != nil {
		return x.DesiredGeneration
	}
	return 0
}

// GetOnboardingResultResponse deliberately contains only non-secret identity
// and plan metadata projected from the committed worker credential. Failed and
// expired outcomes contain only a fixed public error code/summary; raw worker,
// provider, database and credential errors never cross this boundary.
type GetOnboardingResultResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IntentId          string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	AccountId         string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DesiredGeneration uint64                 `protobuf:"varint,3,opt,name=desired_generation,json=desiredGeneration,proto3" json:"desired_generation,omitempty"`
	AuthType          OnboardingAuthType     `protobuf:"varint,4,opt,name=auth_type,json=authType,proto3,enum=execution.v1.OnboardingAuthType" json:"auth_type,omitempty"`
	EmailAddress      string                 `protobuf:"bytes,5,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	OrganizationId    string                 `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UpstreamAccountId string                 `protobuf:"bytes,7,opt,name=upstream_account_id,json=upstreamAccountId,proto3" json:"upstream_account_id,omitempty"`
	Scope             string                 `protobuf:"bytes,8,opt,name=scope,proto3" json:"scope,omitempty"`
	SubscriptionType  string                 `protobuf:"bytes,9,opt,name=subscription_type,json=subscriptionType,proto3" json:"subscription_type,omitempty"`
	RateLimitTier     string                 `protobuf:"bytes,10,opt,name=rate_limit_tier,json=rateLimitTier,proto3" json:"rate_limit_tier,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ProjectedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=projected_at,json=projectedAt,proto3" json:"projected_at,omitempty"`
	// Runtime identity is returned from the same completed workflow binding as
	// the projection. CCMAX needs both values to fence subsequent data-plane
	// requests; neither value is a provider/container identifier or a secret.
	SlotId         string                 `protobuf:"bytes,13,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	ExecutionEpoch uint64                 `protobuf:"varint,14,opt,name=execution_epoch,json=executionEpoch,proto3" json:"execution_epoch,omitempty"`
	Status         OnboardingResultStatus `protobuf:"varint,15,opt,name=status,proto3,enum=execution.v1.OnboardingResultStatus" json:"status,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,16,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorSummary   string                 `protobuf:"bytes,17,opt,name=error_summary,json=errorSummary,proto3" json:"error_summary,omitempty"`
	FinishedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOnboardingResultResponse) Reset() {
	*x = GetOnboardingResultResponse{}
	mi := &file_execution_v1_onboarding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnboardingResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnboardingResultResponse) ProtoMessage() {}

func (x *GetOnboardingResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_v1_onboarding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnboardingResultResponse.ProtoReflect.Descriptor instead.
func (*GetOnboardingResultResponse) Descriptor() ([]byte, []int) {
	return file_execution_v1_onboarding_proto_rawDescGZIP(), []int{4}
}

func (x *GetOnboardingResultResponse) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *GetOnboardingResultResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetOnboardingResultResponse) GetDesiredGeneration() uint64 {
	if x != nil {
		return x.DesiredGeneration
	}
	return 0
}

func (x *GetOnboardingResultResponse) GetAuthType() OnboardingAuthType {
	if x != nil {
		return x.AuthType
	}
	return OnboardingAuthType_ONBOARDING_AUTH_TYPE_UNSPECIFIED
}

func (x *GetOnboardingResultResponse) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *GetOnboardingResultResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetOnboardingResultResponse) GetUpstreamAccountId() string {
	if x != nil {
		return x.UpstreamAccountId
	}
	return ""
}

func (x *GetOnboardingResultResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetOnboardingResultResponse) GetSubscriptionType() string {
	if x != nil {
		return x.SubscriptionType
	}
	return ""
}

func (x *GetOnboardingResultResponse) GetRateLimitTier() string {
	if x != nil {
		return x.RateLimitTier
	}
	return ""
}

func (x *GetOnboardingResultResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GetOnboardingResultResponse) GetProjectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProjectedAt
	}
	return nil
}

func (x *GetOnboardingResultResponse) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *GetOnboardingResultResponse) GetExecutionEpoch() uint64 {
	if x != nil {
		return x.ExecutionEpoch
	}
	return 0
}

func (x *GetOnboardingResultResponse) GetStatus() OnboardingResultStatus {
	if x != nil {
		return x.Status
	}
	return OnboardingResultStatus_ONBOARDING_RESULT_STATUS_UNSPECIFIED
}

func (x *GetOnboardingResultResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetOnboardingResultResponse) GetErrorSummary() string {
	if x != nil {
		return x.ErrorSummary
	}
	return ""
}

func (x *GetOnboardingResultResponse) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

var File_execution_v1_onboarding_proto protoreflect.FileDescriptor

const file_execution_v1_onboarding_proto_rawDesc = "" +
	"\n" +
	"\x1dexecution/v1/onboarding.proto\x12\fexecution.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x02\n" +
	"\x1dCreateOnboardingIntentRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12-\n" +
	"\x12desired_generation\x18\x03 \x01(\x04R\x11desiredGeneration\x126\n" +
	"\x06source\x18\x04 \x01(\x0e2\x1e.execution.v1.OnboardingSourceR\x06source\x12=\n" +
	"\tauth_type\x18\x05 \x01(\x0e2 .execution.v1.OnboardingAuthTypeR\bauthType\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\fR\x06secret\x12\x1c\n" +
	"\tauxiliary\x18\a \x01(\fR\tauxiliary\"\xbd\x02\n" +
	"\x1eCreateOnboardingIntentResponse\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12-\n" +
	"\x12desired_generation\x18\x03 \x01(\x04R\x11desiredGeneration\x126\n" +
	"\x06source\x18\x04 \x01(\x0e2\x1e.execution.v1.OnboardingSourceR\x06source\x12=\n" +
	"\tauth_type\x18\x05 \x01(\x0e2 .execution.v1.OnboardingAuthTypeR\bauthType\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x8e\x02\n" +
	"\x1eRecoverOnboardingIntentRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12-\n" +
	"\x12desired_generation\x18\x03 \x01(\x04R\x11desiredGeneration\x126\n" +
	"\x06source\x18\x04 \x01(\x0e2\x1e.execution.v1.OnboardingSourceR\x06source\x12=\n" +
	"\tauth_type\x18\x05 \x01(\x0e2 .execution.v1.OnboardingAuthTypeR\bauthType\"\x87\x01\n" +
	"\x1aGetOnboardingResultRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12-\n" +
	"\x12desired_generation\x18\x03 \x01(\x04R\x11desiredGeneration\"\xab\x06\n" +
	"\x1bGetOnboardingResultResponse\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12-\n" +
	"\x12desired_generation\x18\x03 \x01(\x04R\x11desiredGeneration\x12=\n" +
	"\tauth_type\x18\x04 \x01(\x0e2 .execution.v1.OnboardingAuthTypeR\bauthType\x12#\n" +
	"\remail_address\x18\x05 \x01(\tR\femailAddress\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\tR\x0eorganizationId\x12.\n" +
	"\x13upstream_account_id\x18\a \x01(\tR\x11upstreamAccountId\x12\x14\n" +
	"\x05scope\x18\b \x01(\tR\x05scope\x12+\n" +
	"\x11subscription_type\x18\t \x01(\tR\x10subscriptionType\x12&\n" +
	"\x0frate_limit_tier\x18\n" +
	" \x01(\tR\rrateLimitTier\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12=\n" +
	"\fprojected_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vprojectedAt\x12\x17\n" +
	"\aslot_id\x18\r \x01(\tR\x06slotId\x12'\n" +
	"\x0fexecution_epoch\x18\x0e \x01(\x04R\x0eexecutionEpoch\x12<\n" +
	"\x06status\x18\x0f \x01(\x0e2$.execution.v1.OnboardingResultStatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x10 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_summary\x18\x11 \x01(\tR\ferrorSummary\x12;\n" +
	"\vfinished_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt*\x83\x02\n" +
	"\x10OnboardingSource\x12!\n" +
	"\x1dONBOARDING_SOURCE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dONBOARDING_SOURCE_SESSION_KEY\x10\x01\x12 \n" +
	"\x1cONBOARDING_SOURCE_OAUTH_CODE\x10\x02\x12!\n" +
	"\x1dONBOARDING_SOURCE_SETUP_TOKEN\x10\x03\x12\x1d\n" +
	"\x19ONBOARDING_SOURCE_API_KEY\x10\x04\x12\x1c\n" +
	"\x18ONBOARDING_SOURCE_COOKIE\x10\x05\x12'\n" +
	"#ONBOARDING_SOURCE_CREDENTIAL_IMPORT\x10\x06*\xa2\x01\n" +
	"\x12OnboardingAuthType\x12$\n" +
	" ONBOARDING_AUTH_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aONBOARDING_AUTH_TYPE_OAUTH\x10\x01\x12$\n" +
	" ONBOARDING_AUTH_TYPE_SETUP_TOKEN\x10\x02\x12 \n" +
	"\x1cONBOARDING_AUTH_TYPE_API_KEY\x10\x03*\xb5\x01\n" +
	"\x16OnboardingResultStatus\x12(\n" +
	"$ONBOARDING_RESULT_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"ONBOARDING_RESULT_STATUS_SUCCEEDED\x10\x01\x12#\n" +
	"\x1fONBOARDING_RESULT_STATUS_FAILED\x10\x02\x12$\n" +
	" ONBOARDING_RESULT_STATUS_EXPIRED\x10\x032\xf1\x02\n" +
	"\x17OnboardingIntakeService\x12s\n" +
	"\x16CreateOnboardingIntent\x12+.execution.v1.CreateOnboardingIntentRequest\x1a,.execution.v1.CreateOnboardingIntentResponse\x12u\n" +
	"\x17RecoverOnboardingIntent\x12,.execution.v1.RecoverOnboardingIntentRequest\x1a,.execution.v1.CreateOnboardingIntentResponse\x12j\n" +
	"\x13GetOnboardingResult\x12(.execution.v1.GetOnboardingResultRequest\x1a).execution.v1.GetOnboardingResultResponseBMZKgithub.com/Wei-Shaw/sub2api/execution-plane/gen/go/execution/v1;executionv1b\x06proto3"

var (
	file_execution_v1_onboarding_proto_rawDescOnce sync.Once
	file_execution_v1_onboarding_proto_rawDescData []byte
)

func file_execution_v1_onboarding_proto_rawDescGZIP() []byte {
	file_execution_v1_onboarding_proto_rawDescOnce.Do(func() {
		file_execution_v1_onboarding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_v1_onboarding_proto_rawDesc), len(file_execution_v1_onboarding_proto_rawDesc)))
	})
	return file_execution_v1_onboarding_proto_rawDescData
}

var file_execution_v1_onboarding_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_execution_v1_onboarding_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_execution_v1_onboarding_proto_goTypes = []any{
	(OnboardingSource)(0),                  // 0: execution.v1.OnboardingSource
	(OnboardingAuthType)(0),                // 1: execution.v1.OnboardingAuthType
	(OnboardingResultStatus)(0),            // 2: execution.v1.OnboardingResultStatus
	(*CreateOnboardingIntentRequest)(nil),  // 3: execution.v1.CreateOnboardingIntentRequest
	(*CreateOnboardingIntentResponse)(nil), // 4: execution.v1.CreateOnboardingIntentResponse
	(*RecoverOnboardingIntentRequest)(nil), // 5: execution.v1.RecoverOnboardingIntentRequest
	(*GetOnboardingResultRequest)(nil),     // 6: execution.v1.GetOnboardingResultRequest
	(*GetOnboardingResultResponse)(nil),    // 7: execution.v1.GetOnboardingResultResponse
	(*timestamppb.Timestamp)(nil),          // 8: google.protobuf.Timestamp
}
var file_execution_v1_onboarding_proto_depIdxs = []int32{
	0,  // 0: execution.v1.CreateOnboardingIntentRequest.source:type_name -> execution.v1.OnboardingSource
	1,  // 1: execution.v1.CreateOnboardingIntentRequest.auth_type:type_name -> execution.v1.OnboardingAuthType
	0,  // 2: execution.v1.CreateOnboardingIntentResponse.source:type_name -> execution.v1.OnboardingSource
	1,  // 3: execution.v1.CreateOnboardingIntentResponse.auth_type:type_name -> execution.v1.OnboardingAuthType
	8,  // 4: execution.v1.CreateOnboardingIntentResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 5: execution.v1.RecoverOnboardingIntentRequest.source:type_name -> execution.v1.OnboardingSource
	1,  // 6: execution.v1.RecoverOnboardingIntentRequest.auth_type:type_name -> execution.v1.OnboardingAuthType
	1,  // 7: execution.v1.GetOnboardingResultResponse.auth_type:type_name -> execution.v1.OnboardingAuthType
	8,  // 8: execution.v1.GetOnboardingResultResponse.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 9: execution.v1.GetOnboardingResultResponse.projected_at:type_name -> google.protobuf.Timestamp
	2,  // 10: execution.v1.GetOnboardingResultResponse.status:type_name -> execution.v1.OnboardingResultStatus
	8,  // 11: execution.v1.GetOnboardingResultResponse.finished_at:type_name -> google.protobuf.Timestamp
	3,  // 12: execution.v1.OnboardingIntakeService.CreateOnboardingIntent:input_type -> execution.v1.CreateOnboardingIntentRequest
	5,  // 13: execution.v1.OnboardingIntakeService.RecoverOnboardingIntent:input_type -> execution.v1.RecoverOnboardingIntentRequest
	6,  // 14: execution.v1.OnboardingIntakeService.GetOnboardingResult:input_type -> execution.v1.GetOnboardingResultRequest
	4,  // 15: execution.v1.OnboardingIntakeService.CreateOnboardingIntent:output_type -> execution.v1.CreateOnboardingIntentResponse
	4,  // 16: execution.v1.OnboardingIntakeService.RecoverOnboardingIntent:output_type -> execution.v1.CreateOnboardingIntentResponse
	7,  // 17: execution.v1.OnboardingIntakeService.GetOnboardingResult:output_type -> execution.v1.GetOnboardingResultResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_execution_v1_onboarding_proto_init() }
func file_execution_v1_onboarding_proto_init() {
	if File_execution_v1_onboarding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_v1_onboarding_proto_rawDesc), len(file_execution_v1_onboarding_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execution_v1_onboarding_proto_goTypes,
		DependencyIndexes: file_execution_v1_onboarding_proto_depIdxs,
		EnumInfos:         file_execution_v1_onboarding_proto_enumTypes,
		MessageInfos:      file_execution_v1_onboarding_proto_msgTypes,
	}.Build()
	File_execution_v1_onboarding_proto = out.File
	file_execution_v1_onboarding_proto_goTypes = nil
	file_execution_v1_onboarding_proto_depIdxs = nil
}
