// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: execution/v1/onboarding.proto

package executionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnboardingIntakeService_CreateOnboardingIntent_FullMethodName  = "/execution.v1.OnboardingIntakeService/CreateOnboardingIntent"
	OnboardingIntakeService_RecoverOnboardingIntent_FullMethodName = "/execution.v1.OnboardingIntakeService/RecoverOnboardingIntent"
	OnboardingIntakeService_GetOnboardingResult_FullMethodName     = "/execution.v1.OnboardingIntakeService/GetOnboardingResult"
)

// OnboardingIntakeServiceClient is the client API for OnboardingIntakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OnboardingIntakeService is an internal mTLS-only CCMAX boundary. Request
// bodies contain temporary credential material and must never be logged.
type OnboardingIntakeServiceClient interface {
	CreateOnboardingIntent(ctx context.Context, in *CreateOnboardingIntentRequest, opts ...grpc.CallOption) (*CreateOnboardingIntentResponse, error)
	// Recover is lookup-only and never decrypts or returns credential material.
	// NOT_FOUND means the exact key was never created; ABORTED means that exact
	// intent expired; FAILED_PRECONDITION means its identity changed or it was
	// claimed/consumed; UNAVAILABLE means durable lookup could not be completed.
	RecoverOnboardingIntent(ctx context.Context, in *RecoverOnboardingIntentRequest, opts ...grpc.CallOption) (*CreateOnboardingIntentResponse, error)
	GetOnboardingResult(ctx context.Context, in *GetOnboardingResultRequest, opts ...grpc.CallOption) (*GetOnboardingResultResponse, error)
}

type onboardingIntakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnboardingIntakeServiceClient(cc grpc.ClientConnInterface) OnboardingIntakeServiceClient {
	return &onboardingIntakeServiceClient{cc}
}

func (c *onboardingIntakeServiceClient) CreateOnboardingIntent(ctx context.Context, in *CreateOnboardingIntentRequest, opts ...grpc.CallOption) (*CreateOnboardingIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOnboardingIntentResponse)
	err := c.cc.Invoke(ctx, OnboardingIntakeService_CreateOnboardingIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardingIntakeServiceClient) RecoverOnboardingIntent(ctx context.Context, in *RecoverOnboardingIntentRequest, opts ...grpc.CallOption) (*CreateOnboardingIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOnboardingIntentResponse)
	err := c.cc.Invoke(ctx, OnboardingIntakeService_RecoverOnboardingIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onboardingIntakeServiceClient) GetOnboardingResult(ctx context.Context, in *GetOnboardingResultRequest, opts ...grpc.CallOption) (*GetOnboardingResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOnboardingResultResponse)
	err := c.cc.Invoke(ctx, OnboardingIntakeService_GetOnboardingResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnboardingIntakeServiceServer is the server API for OnboardingIntakeService service.
// All implementations must embed UnimplementedOnboardingIntakeServiceServer
// for forward compatibility.
//
// OnboardingIntakeService is an internal mTLS-only CCMAX boundary. Request
// bodies contain temporary credential material and must never be logged.
type OnboardingIntakeServiceServer interface {
	CreateOnboardingIntent(context.Context, *CreateOnboardingIntentRequest) (*CreateOnboardingIntentResponse, error)
	// Recover is lookup-only and never decrypts or returns credential material.
	// NOT_FOUND means the exact key was never created; ABORTED means that exact
	// intent expired; FAILED_PRECONDITION means its identity changed or it was
	// claimed/consumed; UNAVAILABLE means durable lookup could not be completed.
	RecoverOnboardingIntent(context.Context, *RecoverOnboardingIntentRequest) (*CreateOnboardingIntentResponse, error)
	GetOnboardingResult(context.Context, *GetOnboardingResultRequest) (*GetOnboardingResultResponse, error)
	mustEmbedUnimplementedOnboardingIntakeServiceServer()
}

// UnimplementedOnboardingIntakeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnboardingIntakeServiceServer struct{}

func (UnimplementedOnboardingIntakeServiceServer) CreateOnboardingIntent(context.Context, *CreateOnboardingIntentRequest) (*CreateOnboardingIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOnboardingIntent not implemented")
}
func (UnimplementedOnboardingIntakeServiceServer) RecoverOnboardingIntent(context.Context, *RecoverOnboardingIntentRequest) (*CreateOnboardingIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverOnboardingIntent not implemented")
}
func (UnimplementedOnboardingIntakeServiceServer) GetOnboardingResult(context.Context, *GetOnboardingResultRequest) (*GetOnboardingResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnboardingResult not implemented")
}
func (UnimplementedOnboardingIntakeServiceServer) mustEmbedUnimplementedOnboardingIntakeServiceServer() {
}
func (UnimplementedOnboardingIntakeServiceServer) testEmbeddedByValue() {}

// UnsafeOnboardingIntakeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnboardingIntakeServiceServer will
// result in compilation errors.
type UnsafeOnboardingIntakeServiceServer interface {
	mustEmbedUnimplementedOnboardingIntakeServiceServer()
}

func RegisterOnboardingIntakeServiceServer(s grpc.ServiceRegistrar, srv OnboardingIntakeServiceServer) {
	// If the following call pancis, it indicates UnimplementedOnboardingIntakeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnboardingIntakeService_ServiceDesc, srv)
}

func _OnboardingIntakeService_CreateOnboardingIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOnboardingIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingIntakeServiceServer).CreateOnboardingIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardingIntakeService_CreateOnboardingIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingIntakeServiceServer).CreateOnboardingIntent(ctx, req.(*CreateOnboardingIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnboardingIntakeService_RecoverOnboardingIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverOnboardingIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingIntakeServiceServer).RecoverOnboardingIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardingIntakeService_RecoverOnboardingIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingIntakeServiceServer).RecoverOnboardingIntent(ctx, req.(*RecoverOnboardingIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnboardingIntakeService_GetOnboardingResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnboardingResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingIntakeServiceServer).GetOnboardingResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardingIntakeService_GetOnboardingResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingIntakeServiceServer).GetOnboardingResult(ctx, req.(*GetOnboardingResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OnboardingIntakeService_ServiceDesc is the grpc.ServiceDesc for OnboardingIntakeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnboardingIntakeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "execution.v1.OnboardingIntakeService",
	HandlerType: (*OnboardingIntakeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOnboardingIntent",
			Handler:    _OnboardingIntakeService_CreateOnboardingIntent_Handler,
		},
		{
			MethodName: "RecoverOnboardingIntent",
			Handler:    _OnboardingIntakeService_RecoverOnboardingIntent_Handler,
		},
		{
			MethodName: "GetOnboardingResult",
			Handler:    _OnboardingIntakeService_GetOnboardingResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "execution/v1/onboarding.proto",
}
